export const SET_GAME = 'SET_GAME';
export const SET_GAME_GRID = 'SET_GAME_GRID';
export const SET_SELECTED_SQR = 'SET_SELECTED_SQR';
export const ACTIVATE_PHASE_TWO = 'ACTIVATE_PHASE_TWO';
export const DEACTIVATE_PHASE_TWO = 'DEACTIVATE_PHASE_TWO';
