export const SET_GAME = 'SET_GAME';
export const SET_GAME_GRID = 'SET_GAME_GRID';
export const SET_SELECTED_SQR = 'SET_SELECTED_SQR';
export const ACTIVATE_PHASE_TWO = 'ACTIVATE_PHASE_TWO';
export const DEACTIVATE_PHASE_TWO = 'DEACTIVATE_PHASE_TWO';

export const SELECTED_GAME = 'SELECTED_GAME';
export const SELECTED_PIECE = 'SELECTED_PIECE';
export const TARGETED_SELF = 'TARGETED_SELF';
export const TARGETED_EMPTY = 'TARGETED_EMPTY';
export const TARGETED_PIECE = 'TARGETED_PIECE';
export const CLOSED_GAME = 'CLOSED_GAME';

// BENCHES FILLED IS THE SAME AS TARGETED SELF